//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Gawa.ACRender.DynamicParser.DataStructures {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataStructures.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/DataStructures.xsd", IsNullable=false)]
    public partial class Structures {
        
        private TypeDef[] typeDefField;
        
        private DataFileDef[] dataFileDefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TypeDef")]
        public TypeDef[] TypeDef {
            get {
                return this.typeDefField;
            }
            set {
                this.typeDefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DataFileDef")]
        public DataFileDef[] DataFileDef {
            get {
                return this.dataFileDefField;
            }
            set {
                this.dataFileDefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataStructures.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/DataStructures.xsd", IsNullable=false)]
    public partial class TypeDef {
        
        private object[] itemsField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Align", typeof(Align))]
        [System.Xml.Serialization.XmlElementAttribute("Field", typeof(Field))]
        [System.Xml.Serialization.XmlElementAttribute("NamedType", typeof(NamedType))]
        [System.Xml.Serialization.XmlElementAttribute("Vector", typeof(Vector))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataStructures.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/DataStructures.xsd", IsNullable=false)]
    public partial class Align {
        
        private int boundaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int boundary {
            get {
                return this.boundaryField;
            }
            set {
                this.boundaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataStructures.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/DataStructures.xsd", IsNullable=false)]
    public partial class Field {
        
        private string nameField;
        
        private FieldType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FieldType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/DataStructures.xsd")]
    public enum FieldType {
        
        /// <remarks/>
        uint32,
        
        /// <remarks/>
        uint16,
        
        /// <remarks/>
        @byte,
        
        /// <remarks/>
        single,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataStructures.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/DataStructures.xsd", IsNullable=false)]
    public partial class NamedType {
        
        private string typeNameField;
        
        private string displayNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataStructures.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/DataStructures.xsd", IsNullable=false)]
    public partial class Vector {
        
        private object itemField;
        
        private string nameField;
        
        private string lengthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Align", typeof(Align))]
        [System.Xml.Serialization.XmlElementAttribute("Field", typeof(Field))]
        [System.Xml.Serialization.XmlElementAttribute("NamedType", typeof(NamedType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataStructures.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/DataStructures.xsd", IsNullable=false)]
    public partial class DataFileDef {
        
        private object[] itemsField;
        
        private string nameField;
        
        private uint matchmaskField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Align", typeof(Align))]
        [System.Xml.Serialization.XmlElementAttribute("Field", typeof(Field))]
        [System.Xml.Serialization.XmlElementAttribute("NamedType", typeof(NamedType))]
        [System.Xml.Serialization.XmlElementAttribute("Vector", typeof(Vector))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint matchmask {
            get {
                return this.matchmaskField;
            }
            set {
                this.matchmaskField = value;
            }
        }
    }
}
